### ISSUE TITLE
pod 的页面交互操作

### ISSUE THREAD

**Issue by caoyingjunz** [pixiu-io/dashboard#74]
页面点一下，弹一个黑框出来，可以占大半个屏幕，右上角有个x可以关闭，然后在黑框内可以进行pod内部命令行操作

![image](https://user-images.githubusercontent.com/53616187/195978568-6d6e1326-d226-4ec9-a8a6-82d4d2ca17a9.png)
![image](https://user-images.githubusercontent.com/53616187/195978628-430b92de-1c16-43fc-a535-4d4381958ab4.png)

**Comment by caoyingjunz** [comment]
实现集群的webshell

**Comment by noovertime7** [comment]
pick pick
